# Generated by Django 4.2.7 on 2025-03-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="document_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("TI", "Tarjeta de Identidad"),
                    ("CE", "Cédula de Extranjería"),
                    ("PP", "Pasaporte"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
