# Generated by Django 4.2.7 on 2025-03-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="products/default.jpg",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
